### ISSUE TITLE
Document how to create an event

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [python-sprints/python-sprints.github.io#110]
This is for other groups use. Should include pictures to make it super easy i think. Should include info on what variables are needed, what are optional and what images can be used. Best test would be to give the task to someone unfamiliar with the project of creating an event according to this instruction :).
Related to: #98

**Comment by datapythonista** [comment]
@Tomasz-Kluczkowski I don't have much time these days, but if you, this is the only ticket preventing other chapters from starting using our website. @Cheukting, if you want to get started in the website, that could be a great first issue. :)

**Comment by datapythonista** [comment]
Fixed in ff91a7e8fceeb1695d149c1442a7f84d08ace968
