### ISSUE TITLE
Document how to create a chapter

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [python-sprints/python-sprints.github.io#111]
Same as #110 - This is very important for other groups to be able to use this site. Detailed instruction should be provided on how to make their own chapter - what variables are necessary to provide, what are optional, how to add images and what size etc.

**Comment by datapythonista** [comment]
This was mainly implemented in the project README file. We just need to review that we didn't make changes to the chapter files that make the documentation outdated.

**Comment by datapythonista** [comment]
Fixed in ff91a7e8fceeb1695d149c1442a7f84d08ace968
