### ISSUE TITLE
Unify look of events / chapters cards at home page.

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [python-sprints/python-sprints.github.io#117]
To keep looks matching I would like to convert events card to look similar to chapters card at the home page view. It may require removing div inside column design and going with card / column that is used for chapters cards.

**Comment by datapythonista** [comment]
I'm playing with the website, and it's really a great job. I'm writing instructions for organizers of other groups to be able to add their chapters, sponsors and events. I'll probably "simplify" a bit the structure.

Besides that, there is just one thing I'd really like to change. My eyes really get confused/tired with the colours and boxes of the events and chapters. I'd rather have something minimal and simple with a white background. So, before you take care of this ticket (or anything related), let's discuss a bit about that part please. :)

**Comment by Tomasz-Kluczkowski** [comment]
Hey,

It’s great someone helps :)
Do you mean something like the simple card version here:
https://getbootstrap.com/docs/4.0/components/card/

Find the one that says „Header and footer” in the title.

I will see how it fits into the color scheme of the site so far. The background is quite dark in this section so white card will be visible and then dark writing on top of it - but will it look good?


How would you like to simplify the structure? I guess remove certain yml variables and show less info on the screen? :).
We can always remove :). Adding is harder.


On 24 Mar 2018, at 19:51, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm playing with the website, and it's really a great job. I'm writing instructions for organizers of other groups to be able to add their chapters, sponsors and events. I'll probably "simplify" a bit the structure.

Besides that, there is just one thing I'd really like to change. My eyes really get confused/tired with the colours and boxes of the events and chapters. I'd rather have something minimal and simple with a white background. So, before you take care of this ticket (or anything related), let's discuss a bit about that part please. :)

**Comment by datapythonista** [comment]
I don't know exactly, but something with lighter colors, not so many lines (header, button...), where the style doesn't keep the attention more than the content (texts). For some sections it's great that the website is cool. But for the events, I'd like to be as clear as your inbox or todo list, no distractions.

This for example seems a bit more what I'd like: https://www.last.fm/events

For simplifying, just moving all the ipad/iphone icons into a directory, and `_posts` to the root, is probably all what I mean. So it's easier to find things, and I can tell organizers just to create their event in `_posts` instead of "create a directory with you group name in lowercase in chapter_events, then a _posts inside, and there you place your event".

Also, I was experimenting with having a `_projects` collection, but Jekyll have many limitations, and it's difficult to do exactly what I want.

**Comment by Tomasz-Kluczkowski** [comment]
Ok stuff gets complicated and we need to talk on the phone / skype as I need to explain how stuff works now in jekyll and then we can make sensible decisions :). I am at work today but I can talk when at home in the evening. Let me know if you have some time and at what time.
Skype is ok I was actually thinking of some webinar software that allows sharing desktops and talking at the same time.
It looks though that they are chargable.
Have to investigate and find one that is free and works.

If you cannot talk today then let me know when please.
This will save us a lot of writing back and forth :).
Nothing better than an image, worth 10k words...
I will send my mumber on the private channel:).



On 25 Mar 2018, at 11:11, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know exactly, but something with lighter colors, not so many lines (header, button...), where the style doesn't keep the attention more than the content (texts). For some sections it's great that the website is cool. But for the events, I'd like to be as clear as your inbox or todo list, no distractions.

This for example seems a bit more what I'd like: https://www.last.fm/events<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.last.fm%2Fevents&data=02%7C01%7C%7Cc9d7b6a2e6164ea426d208d59238d121%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636575695074132873&sdata=08bCouwTzd1Dne0BIjqF9q7MQZqqbplJ58qHis7Emes%3D&reserved=0>

For simplifying, just moving all the ipad/iphone icons into a directory, and _posts to the root, is probably all what I mean. So it's easier to find things, and I can tell organizers just to create their event in _posts instead of "create a directory with you group name in lowercase in chapter_events, then a _posts inside, and there you place your event".

Also, I was experimenting with having a _projects collection, but Jekyll have many limitations, and it's difficult to do exactly what I want.

**Comment by Tomasz-Kluczkowski** [comment]
Closed as both events and chapters now have list like view.
