### ISSUE TITLE
Further clean up of old stuff

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#130]
I think there is still some stuff that can be done to make the source code simpler. I'm probably wrong in some cases, but this is what I'd do:
- Remove ./2018
- Move ./DOCS to ./docs
- Remove ./old_files
- Remove ./pull_request_intro
- Move ./site_icon to ./static/icons
- Remove ./temp

@Tomasz-Kluczkowski what do you think?

**Comment by Tomasz-Kluczkowski** [comment]
No probs. I’ll look into it. Things got a bit hectic on my side :). And my kid is on holiday  so I have a bit less time but I want to make this site as beautiful as possible :). Codewise and lookwise too.

I noticed that you overrode the h1-2-3 font settings - I will have to reinplement that as it creates sizing issues when page loads etc. I will amend the global settings to reflect your sizes later on. I am avoiding setting anything in pixels as it will not scale well on different devices (where the pixels get really small, the font gets really small too). I use relative (em, rem, %) units for everything and set global font size on html or body in % of the default (which I believe is 16px).

I will fix it hopefully towards the end of the week :).

On 11 Apr 2018, at 21:17, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


I think there is still some stuff that can be done to make the source code simpler. I'm probably wrong in some cases, but this is what I'd do:

  *   Remove ./2018
  *   Move ./DOCS to ./docs
  *   Remove ./old_files
  *   Remove ./pull_request_intro
  *   Move ./site_icon to ./static/icons
  *   Remove ./temp

@Tomasz-Kluczkowski<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTomasz-Kluczkowski&data=02%7C01%7C%7C072bec34a97b4c7e441c08d59fe9502d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636590746770238114&sdata=ESGe9eZihtT%2FoHomDMjQv5R4rRu02h56pj4nyRoZ51c%3D&reserved=0> what do you think?

**Comment by datapythonista** [comment]
I'm happy to take care of this. I created the ticket so it could be some discussion, on whether there is something we want to keep, or whether the renaming I propose makes sense.

**Comment by Tomasz-Kluczkowski** [comment]
Moving the site_icons will require adjusting the paths to the icons in head.html and other files - we did this as I think issue #125 on last meetup(merged) I should have asked for it to be moved to static straight away :).
If you can do that it would be great.

Yes we have to clean up the projects folders. I will check if there is no stuff I need to have a local copy of and let you know asap.

On 12 Apr 2018, at 12:51, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm happy to take care of this. I created the ticket so it could be some discussion, on whether there is something we want to keep, or whether the renaming I propose makes sense.

**Comment by datapythonista** [comment]
Git keeps the whole history of the repo. We can easily recover any deleted file without having any local copy. :)

**Comment by Tomasz-Kluczkowski** [comment]
Hehe you learn all day every day. Sooner or later my head will explode but this Saturday I am going out as grandma is looking after my daughter and will do a „hard reset” of my brain :).

Sure, I checked anyway and I have all that stuff locally if I need it and as you say - we can magick it back to life at any time as well.

I leave this issue in your hands then and I will finish chapters view and fix styling of titles site-wide.

On 12 Apr 2018, at 13:32, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


Git keeps the whole history of the repo. We can easily recover any deleted file without having any local copy. :)

**Comment by Tomasz-Kluczkowski** [comment]
Done in 1ba05c85852ae8026d7467dedc34b19c7cdeb8cd
