### ISSUE TITLE
Avoid duplicate id for chapters

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#131]
Seems like we're using two different identifiers for chapters, `obj_id` and `category`. I think this can be avoided, and make things easier.

I guess `category` is the standard Jekyll way we want to keep. Not sure if we can simply delete `obj_id` or this affects some part using it.

So, in this ticket we should:
- Get rid of `obj_id` in the London chapter
- Move `category` to be the first field
- Use `category` instead of `obj_id` in any code using it
- Update `README.md` section "How to create your chapter"

**Comment by Tomasz-Kluczkowski** [comment]
Ok I back out of this and will just keep the city name as the category as it makes it simple to use it also as a  reduced address for the group (as it is now). 
We do not think there could be more than 1 group in a given city do we ?

**Comment by Tomasz-Kluczkowski** [comment]
Done in: 81f5442aab05268c0d1aac4a5cf952e4affaed99
Also updated README.md on quite a few things.
You may want to have a look in there.
I did it quickly so probably need to fix inconsistencies in naming things and wrapping variables in <> or "".

**Comment by datapythonista** [comment]
Happy to use simply "london", if some other group in London joins they'll have to pick a more verbose name, as "london" will be taken. :)
