### ISSUE TITLE
Sprints are hidden in the home page the day of the sprint

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#132]
We should keep the events in the home page until the day after the sprint, not hide them the same day of the sprint.

**Comment by Tomasz-Kluczkowski** [comment]
Done in 013f40d468de6a3401a0fbe2ad1e1623d2b0f113
Atm the solution is quite primitive but tested to work in our timezone at least. 
I am not sure how this works in different timezones though.
