### ISSUE TITLE
Document where the photo of the chapter page comes from

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#133]
I didn't see a field for it in the chapters `.md` page, so I assume it's supposed to be named as the chapter and placed in a directory. We should add how to have it in the section "How to add your chapter" in `README.md`.

**Comment by Tomasz-Kluczkowski** [comment]
I have it hardcoded with srcset atm for our user group. I will have to find a way of making it dead simple (use only one img) for the users and at the same time that the image will scale and crop properly on landscape and portrait modes.

**Comment by Tomasz-Kluczkowski** [comment]
Done in: 6390a84e4337396785b80da3329d5a42f25fcdb7
