### ISSUE TITLE
See if we can get rid of the date in the event fields

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#134]
It's already in the file name, it'd be great to use that one, and not have it repeated.

**Comment by Tomasz-Kluczkowski** [comment]
Should be doable. The date field is to allow overriding the file one in case of creating an event with a future date but I think jekyll can uses the date from the file name as long as it is formatted correctly.

**Comment by Tomasz-Kluczkowski** [comment]
Done in: 81f5442aab05268c0d1aac4a5cf952e4affaed99
