### ISSUE TITLE
change pictures on home page from png to jpeg - site takes > 1second to load!

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [python-sprints/python-sprints.github.io#135]
All the images used need converting to jpeg and compressing as it takes more than a second to load the home page now.

Are all originals from the pandas twitter thread Marc ?

**Comment by datapythonista** [comment]
I think so.

**Comment by Tomasz-Kluczkowski** [comment]
Done in d57356656ba49e4e1dd486f9f2cc2f019d8953bc
