### ISSUE TITLE
Create a contact page and form

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [python-sprints/python-sprints.github.io#21]
I know you are extremely busy but I am done with my presentation for London Python and can work a bit more on the Python Sprints website and need some answers please.

I would like to create a simple contact page and from.
Naturally exposing the contact email is a very silly idea (Bots!!) so since we do not have a backend I want to use this free of charge, no sign up service:
https://formspree.io. 

It just redirects to given email. Is this ok?

What will be the email address that should contact froms be sent to?

**Comment by datapythonista** [comment]
We've got a gmail address, the same as the twitter username, but with a dot instead of the underscore.
