### ISSUE TITLE
Add option to hide sponsors

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#30]
It'd be nice in the files in `_sponsors` to have a new field like `show_in_home` or something like that, and be able to specify the ones that we want to show. I'd prefer to avoid having Zopa that just sponsored once a while ago (and others in the future), as it feels unfair to sponsors like Harvey Nash who are sponsoring us every month.

**Comment by Tomasz-Kluczkowski** [comment]
Great idea!
Adding to my list on the wall :)

On 28 Feb 2018, at 20:19, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


It'd be nice in the files in _sponsors to have a new field like show_in_home or something like that, and be able to specify the ones that we want to show. I'd prefer to avoid having Zopa that just sponsored once a while ago (and others in the future), as it feels unfair to sponsors like Harvey Nash who are sponsoring us every month.

**Comment by Tomasz-Kluczkowski** [comment]
This has now been resolved.

**Comment by datapythonista** [comment]
Amazing, great job with the website. I was taking a quick look at the code too, and looks really great, we should open source it and make it available to other meetups. :)

**Comment by Tomasz-Kluczkowski** [comment]
Hehe thx, Liquid is awkward but assembler was harder :). It will be one of the projects to mention on my CV definitely.
 There is a long list on my wall of stuff to make better (automatic image source set generation for example) but next I want to create a list view of upcoming and past events (all on one page) - events section.
After that I want to make about section but need our "family" photos for that - we should try to take them on 10th at Bloomberg.
