### ISSUE TITLE
Add section for Windows in pandas set up guide

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#40]
Pandas set up guide assumes Linux or Mac is being used, and it'd be nice to have a section for Windows users too (mainly on how to install a compiler, not sure if there are other things).

This has been suggested by @jorisvandenbossche in https://github.com/python-sprints/python-sprints.github.io/pull/39#issuecomment-369752490 and previously by @dukebody too.

@Cheukting I think you're probably the right person for the job. ;) Do you have time to take a look at it?

**Comment by jorisvandenbossche** [comment]
There is a very small section on that in the pandas guide: http://pandas-docs.github.io/pandas-docs-travis/contributing.html#installing-a-c-compiler (with some links), but not very user friendly.

**Comment by Cheukting** [comment]
Sure I will, will based on the official guide and may be add my own tip (as it was a pain for me to install a compiler)

**Comment by Cheukting** [comment]
I have checked, basically for Window users they need to install different *things* (I cannot find a better word as it is so complicated). The best guide is a table in here: https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/

If we can include the table and the links to the download page for those *things* they need then I think it's fine :-)

Let me know if you want me to commit a file, if so tell me in what format you want.

**Comment by datapythonista** [comment]
Ideally we want concise instructions on how to set up an environment to contribute to pandas in this document:
https://github.com/python-sprints/python-sprints.github.io/blob/master/pandas/guide/source/pandas_setup.rst

I don't have much idea on what is required, so can't really tell how it should fit in the current instructions. But what it comes to my mind is that we replace the current `Instructions` title by a `Instructions for Linux and Mac` and at the end we have a `Instructions for Windows` section.

If that's a good idea (assuming almost everything is different), then we could move the "Create a GitHub account" to the pre-requisits and start each section by the "Get pandas source code", which I assume in Windows people can do it with a right click or something like that. Then, not sure how Anaconda works in Windows, if it's the same from a DOS terminal or what.

Or if you think that everything is mostly the same, just the compiler part, you can just change the section "Compile C code in pandas" to "Compile C code in pandas (Linux and Mac)" and then add a Windows one just for that block.

It's totally up to you. If you leave it as you'd like to have it the day you were installing all this stuff, that would be really great, and appreciated by tens of Windows users during the sprint. :)

**Comment by Cheukting** [comment]
Sure, I will do it over the weekend. By the way, I don't think Window user can go a git clone in cmd (it won't know the commend `git`) they will need a git bash. For Anaconda it is more or less the same, they just need to do those commend on an Anaconda Prompt.

I will add instruction for Windows for Git and C compiler section mainly, may add comments for Anaconda.

**Comment by Cheukting** [comment]
PR #47 sent
