### ISSUE TITLE
About section and progress report / questions

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [python-sprints/python-sprints.github.io#57]
Marc,

**I do not expect** you to answer this before 10th of March so do not worry - focus on Pandas event.
It looks awsome, so many chapters !!!! Makes me feel part of something really big. Shame no one in Poland does anything :(.

- I want to create about section now (events is more or less ready).
- will need some photos (group ones and some close-ups if people don't mind)
I would like your photo, other organisers, possibly mine, Hamish's - anybody else who tries to help us regularly.
- Could we request Bloomberg to have some photo camera better than my ageing iphone when we have the Pandas event ?

- Below the header I want some writing about what we do, how it all started - your help will be needed (I will try to squeeze some "founding myths" :) from you during break time or after the event on 10th of March if we go for some beers (I hope) to celebrate)

- Below that - meet the team section.
I would like to stick you Marc in there as the founder, organiser, leader etc. - hope you don't mind :)
I would like to also mention that I worked my fingers a lot to make this website :) - hope that is ok.
I am thinking also about putting Hamish as a co-organiser as he really supports our efforts.
Anybody else??

- If you disagree with anything (as it gets to more personal stuff like photos and such) I will understand.
I am asking for your opinion as I feel we gotta shape this together eventually.

C u,

Tomasz

**Comment by datapythonista** [comment]
I hope we can get some good pictures on Saturday. Happy to have you as the author of the web, and the sponsors highlighted in the website. But I don't really like to create the feeling that the group is about anyone in particular, but about the whole open source and Python community helping each other, working together and having fun. So, it'll be great to have pictures of the sprints, or us drinking beers, but I prefer to avoid having any organizer in the website. Organizers will keep changing, and some individuals will come and go. But the values of open source, of building together, sharing, and having fun, will remain, and this is the idea I'd like to see in the website.

**Comment by Tomasz-Kluczkowski** [comment]
Thx, that’s exactly what I needed as a source of inspiration for how to shape the about page :).
Let’s have a good one on Saturday!

On 6 Mar 2018, at 21:57, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


I hope we can get some good pictures on Saturday. Happy to have you as the author of the web, and the sponsors highlighted in the website. But I don't really like to create the feeling that the group is about anyone in particular, but about the whole open source and Python community helping each other, working together and having fun. So, it'll be great to have pictures of the sprints, or us drinking beers, but I prefer to avoid having any organizer in the website. Organizers will keep changing, and some individuals will come and go. But the values of open source, of building together, sharing, and having fun, will remain, and this is the idea I'd like to see in the website.

**Comment by Tomasz-Kluczkowski** [comment]
Marc,

About section done (with rubbish photos sadly, I did my best though).
Please review when you finish with pandas( i expect at least a week before you are done :)).
Unfortunately no one provided any photos :(.
I used mine but I only have an ancient Iphone 6 and quality is miserable.
Will have to replace those photos as we go and get better ones.

What do we want in getting started?
I guess we already have some tutorials worked out?
I remember that Cheuk was working on some guide for Pandas on beloved Windowz and we should have some guide on making contribution for the first time as well somewhere.
I would just make links to those then.

Lastly i will (in some time) create a credits page with thanks to all the people whos photos I am using and mentioning my name in there as a creator/designer of this site (unless you want me to just stick it at the bottom of the footer, but I managed to keep all the names out of the site so far)

I need to focus now on my other studies as well so will work a bit less on this site but it also needs documentation now :) ( does it ever end?!) - I will slowly work on it in my spare time so that anyone can add content later on easily.

Talk to you later when you are less busy with pandas :).

Tomasz

**Comment by datapythonista** [comment]
Hey Tomasz,

The page looks really cool. There is something that came to my mind (spoiler: it will give you/us more work ;).

Seems like there is a lot of interest in sprinting, since our amazing #pandasSprint. And I think it'd be nice to use the website, not only for our sprints in London, but for anyone in the Python community doing sprints.

We all have meetup pages that we use, so even if we get lots of events (I wish), shouldn't be a problem as each group will access mainly from links from their site.

With the system you built, any chapter can just add  a .md file for an event, send a pull request, and get it into the page as easy as with meetup (or more, meetup interface is crap).

How I see it (and it's just an idea), it's that for it, the website should be a bit more functional. Meaning that instead of using the whole home page for messages selling the group (missing, what we do...), we could have a longer list of events, links to the documentation, may be a map with the meetups that host sprints (similar to the one in the pandas sprint)...

The good news is that for photos, you can use  all the ones from the different sprints. There are many with the hashtag #pandasSprint.

We're having 2 sprints next week, Tuesday and Thursday. If you're coming, you can lead a group with everybody interested in working in the website.

Those are just random ideas, I'm sure you have better ones, but I think something like that would be cool, right?

**Comment by Tomasz-Kluczkowski** [comment]
This is the next step that I was considering :) but naturally now it is a lot of work and requires some planning together - we need to get a piece of paper and draw what sections to move where.
Also it would have to be conflict free so probably each chapter would have to have its own events folder.
I am not sure how Jekyll deals with nested posts folders - have to investigate but I believe it is possible.

Site is pretty much modular (or as close as I could make it in Jekyll) so moving stuff around should not be a big issue. I have no probs cutting stuff out of the home page :).
Trouble is people do not seem to be interested in working on the site itself :(.
I would like to come to one of the sprints next week but 2  is impossible - my wife will start a strike action :).
I can see one meetup event on Tuesday for Pandas and what is the Thursday one?
Are they both in Harvey Nash?
C u next week.

**Comment by Tomasz-Kluczkowski** [comment]
Preliminary solution to creating chapters (untested)
@parkr if like macta said i create directories like blog1/_posts and blog2/_posts what is the code i need to filter only the blog1 (or the blog2) posts in my default layout ? The goal is to not add special keyword front matter of each post to differenciate if it is a blog1 or a blog2 post.
@JrCs it automatically applies the blog1 or blog2 categories:

{% for post in site.categories.blog2 %}
    {{ post.title }}
{% endfor %}

**Comment by Tomasz-Kluczkowski** [comment]
Closed as enough info obtained.
