### ISSUE TITLE
The pandas folder - deleted files

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [python-sprints/python-sprints.github.io#7]
Hi Marc,

Git is reporting this:

        deleted:    _static/index.html (this on actually I deleted myself)
        deleted:    pandas/bower_components/bootstrap/dist/css/bootstrap.min.css
        deleted:    pandas/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
        deleted:    pandas/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
        deleted:    pandas/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
        deleted:    pandas/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
        deleted:    pandas/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
        deleted:    pandas/bower_components/bootstrap/dist/js/bootstrap.min.js
        deleted:    pandas/bower_components/ionicons/css/ionicons.min.css
        deleted:    pandas/bower_components/ionicons/fonts/ionicons.eot
        deleted:    pandas/bower_components/ionicons/fonts/ionicons.svg
        deleted:    pandas/bower_components/ionicons/fonts/ionicons.ttf
        deleted:    pandas/bower_components/ionicons/fonts/ionicons.woff
        deleted:    pandas/bower_components/jquery/dist/jquery.min.js
        deleted:    pandas/bower_components/smooth-scroll/dist/js/smooth-scroll.min.js

It was like that when I cloned the python-sprints repo. I am assuming you have deleted those files? Can I safely push this and get rid of them?. I have pandas/bower_components/ in gitignore but this keeps popping up all the time annoying me :).

BTW. started working on adapting site to jekyll today.

**Comment by datapythonista** [comment]
No, those files haven't been deleted, they're on the server, git is reporting that they've been deleted in your computer, no idea why, but please DON'T push those changes, that would break the pandas sprint website, which will be promoted today by the PSF and NumFOCUS.

**Comment by Tomasz-Kluczkowski** [comment]
Ok thats why I didnt push :).
I am resonable enough to assume you need them :).

On 12 Feb 2018, at 11:24, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


No, those files haven't been deleted, they're on the server, git is reporting that they've been deleted in your computer, no idea why, but please DON'T push those changes, that would break the pandas sprint website, which will be promoted today by the PSF and NumFOCUS.
