### ISSUE TITLE
Update website with the new icon

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#82]
![python_sprints_logo](https://user-images.githubusercontent.com/10058240/37409147-7f86e572-2795-11e8-836a-14e5c3483354.png)
![python_sprints_logo_dark_bg](https://user-images.githubusercontent.com/10058240/37409148-7fc0c5d0-2795-11e8-89cf-f8b4e086d50a.png)
![python_sprints_logo_only](https://user-images.githubusercontent.com/10058240/37409149-7fdb24de-2795-11e8-9f98-4f42d15bb2ad.png)

**Comment by Tomasz-Kluczkowski** [comment]
Started working on this and the light text version presents itself beautifully as the main logo replacing the „Python Sprints” text in the home page. I should push this change today/tomorrow once I adjust the size for mobiles in different orientations.

I would like to also stick it where the brand is (top left corner) and in the footer. But to do that I need a flattened version (text going horizontally, unstacked). Any chance the author of this can do another version please?
I can do it myself but it’s not my own work so I do not want to modify it without permission :).

**Comment by Tomasz-Kluczkowski** [comment]
Even better: if they could give me the text separately to the logo in the flat horizontal version in lght and dark color please.

Then I can adjust the size of the icon separately from the text size. 

In the navigation the logo is only 28px high. Can make it slightly higher but not too much or it will take too much space on mobiles.

**Comment by datapythonista** [comment]
![python_sprints_logo_flat_dark_bg](https://user-images.githubusercontent.com/10058240/37465994-8e99b3a4-2854-11e8-9c74-ffc0a87888c7.png)
![python_sprints_logo_flat_light_bg](https://user-images.githubusercontent.com/10058240/37465996-8eb9f48e-2854-11e8-8f9b-d3c0cc66e281.png)

Is that it, right?

**Comment by Tomasz-Kluczkowski** [comment]
Spot on :)
Thx


On 15 Mar 2018, at 13:27, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


[python_sprints_logo_flat_dark_bg]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F10058240%2F37465994-8e99b3a4-2854-11e8-9c74-ffc0a87888c7.png&data=02%7C01%7C%7Ce2d0ccf138874de7c0ae08d58a787a97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636567172404198788&sdata=9uVRasCUmculbfldWCkUTA1ws5mD1BnInBpM4gik%2FnA%3D&reserved=0>
[python_sprints_logo_flat_light_bg]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F10058240%2F37465996-8eb9f48e-2854-11e8-8f9b-d3c0cc66e281.png&data=02%7C01%7C%7Ce2d0ccf138874de7c0ae08d58a787a97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636567172404198788&sdata=kYh2dkkc3%2BimdHuCzRGmNdPabUPIPd%2BKL4ZDwSGnL6s%3D&reserved=0>

Is that it, right?

**Comment by Tomasz-Kluczkowski** [comment]
#82 Done.
Favicon pack for all major systems also added so that if anyone creates a favourite with a link to python sprints website it looks nice. Those files have to be in the root.

**Comment by Tomasz-Kluczkowski** [comment]
Could I have the author of the logo so that he/she can be added to the credits page please?

**Comment by datapythonista** [comment]
Marcel Garcia
https://www.linkedin.com/in/marcelgarciadesigner/
