### ISSUE TITLE
Create chapter detailed view

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [python-sprints/python-sprints.github.io#97]
We need to create chapter's detailed view. As an inspiration please use the about page (header image at least and title font).
This section should contain details of a particular sprint group - their location, short history, some projects they work on etc.

**Comment by datapythonista** [comment]
Isn't this already implemented? I'm happy with the current chapter page.

**Comment by Tomasz-Kluczkowski** [comment]
It is if you are happy :). Even the logos for harvey nash and bloomberg got fixed.
I will close it then.

On 17 Apr 2018, at 10:26, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


Isn't this already implemented? I'm happy with the current chapter page.

**Comment by Tomasz-Kluczkowski** [comment]
Closed
